app.controller("experienceController", function ($scope) {

  // modal and used code based on http://www.w3schools.com/howto/howto_css_modals.asp
  var modal = document.getElementById('myModal');
  var span = document.getElementsByClassName("close")[0];

  span.onclick = function() {
    modal.style.display = "none";
  }

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }

  // Generate the HTML content about the projects I worked on at different company.
  $scope.displayModal = function displayModal(company) {
    modal.style.display = "block";

    switch(company){
      case 'viasat':
        var HTMLcontent =
          "<p>Internship at ViaSat:</p>" +
          "<p>The project's major accomplishments was providing user authentications and authorization a internal web app that provided statistical analysis of test data from the company's satellite, handheld, and radio products. Prior to the summer internship, the web app's only form of security that a user had to be connected to the company network when using the site.</p>" +
          "<p>The first project accomplishment that was implemented was user authentication through company SSO, by installing a web agent onto our IIS server in order to communicated with the company's existing SSO services.</p>" +
          "<p>Second project accomplishment was implementing user authorization that would limit user to see the data they've been given permission to. I created the necessary SQL data schema, stored procedures and queries, backend .NET Web API, and frontend UI elements that enable a user to make request for specific data to their managers before they are allowed to see data on the site.</p>" +
          "<p>By the end of the summer internship, both user authentication and authorization features were completed and being tested against live production data set. These features will be part of the next major version release.</p>";
          break;
      case 'jpl2':
        var HTMLcontent =
            "<p>Second internship at JPL:</p>" +
            "<p>The project's major accomplishments was providing a working prototype of a new internal web app that ultimately helped secure funding from other teams for further development.</p>" +
            "<p>This web app served as a interface to a Engineering Management System (EMS), which is an engineering management platform that allowed engineers to share modeled data. The web app specifically focused on providing launch system data, such as launch vehicle specifications and launch opportunities.</p>" +
            "<p>The data is generated by parsing EMS's RESTful API so that there is no additional work to update the content. Another important feature was creating data visualizations that pulled data from multiple launch systems and using a data charting library to plot them together. This allowed interactive data visualizations that helped a user compare performance and specifications of different launch vehicles</p>" +
            "<p>Presentations of the prototype were made to managers and teams around JPL, which resulted in high interest and additional funding to develop more features for the site. This allowed us to add an UX designer, a software engineer, and one more intern to the team.</p>";
          break;
      case 'grc':
        var HTMLcontent =
            "<p>Internship at Glenn Research Center:</p>" +
            "<p>The project's major accomplishments was providing two major features to the Space Communication and Navigation team's Optical Satellite Link Assessment Tool. This tool calculated link budget dynamically over the span of an entire mission scenario. Link budget is an accounting of all gains and losses from the transmitter to the receiver in a telecommunication system, which in this case is between an orbiting satellite on another planet and a ground station.</p>" +
            "<p>The first accomplishment was implementing a solver feature can calculate what-if scenarios. This feature saved the user time from manually tuning the calculators to get the results they want. For example, the user specific the decibels of link margin they want and ask the solver to find the corresponding input value in one of the input parameter, such as data rate. </p>" +
            "<p>The second accomplishment was adding a simulation of background irradiance seen by a receiver into the calculation. As the receiver looks up into the sky at the satellite, objects in the background such as stars give off an irradiance that can effect the calculators. Using a physic based software Systems Tool Kit and its API, I simulated this effect and incorporated the backgound irradiance values into the link budget calculations. This feature helped the tool calculate link budget more accurately by a few precentage points</p>" +
            "<p>Both feature were completed by the end of summer. An abstract of the work was submitted to the 2015 International Astronautical Congress conference, and I was invited to present this work at the young professionals forum. The abstract to my presentation can be found here: <a href='https://iafastro.directory/iac/archive/browse/IAC-15/B2/8-YPVF.3/31676/'>https://iafastro.directory/iac/archive/browse/IAC-15/B2/8-YPVF.3/31676/</a></p>";
          break;
      case 'jpl':
        var HTMLcontent =
            "<p>First internship at JPL:</p>" +
            "<p>The project's major accomplishments was turning a series of MATLAB scripts that validated the data collected on an airborne spectrometer into a GUI based software. This project was done under the guidance of the AVIRIS team. <a href='http://aviris.jpl.nasa.gov/'>http://aviris.jpl.nasa.gov/</a></p>" +
            "<p>A powerful spectrometer is mounted on an airplane, so that it can fly over a section of the Earth taking frames of the ground. This allows Earth scientist to view image of the ground in a large range of spectra. The MATLAB scripts validated the data collected against any data loss, correctness of GPS coordinates, and its synced between the taken frames and the GPS coordinates.</p>" +
            "<p>Before the internship there were multiple scripts that did something similar, e.g. one for an old version of the spectrometer, one for a new one, and one that validated data for an entire directory instead of single file. They each also shared some similar code. I refactored the code in a OOP style that helped eliminated some duplicate code and improved maintenance going forward. I also helped create a GUI using MATLAB GUIDE.</p>" +
            "<p>At the end of the internship, users were able to use the software as a single GUI application instead of a series of MATLAB scripts. The code also became much more maintainable in an OOP style.</a></p>";
          break;
      default:
        var HTMLcontent =
            "<p>Oops, nothig here!</p>";
        break;
    }

    document.getElementById("modalMsg").innerHTML = HTMLcontent
  }
});